<?php

use Database\Seeders\DemoImageManifest;

/**
 * MUTYA STORE — Demo product-image fetcher (development / academic use only).
 *
 * Standalone script (no composer/Laravel required) that downloads one
 * royalty-free placeholder photograph per product that has NO images yet,
 * saving them exactly where the admin uploader puts files:
 *     storage/app/public/products/<file>.jpg
 * and printing ready-to-run SQL for the frozen `product_images` table.
 *
 * Image source: curated hijab / modest-fashion photography from Pexels,
 * defined in DemoImageManifest.php (category slug -> verified photo id),
 * downloaded into LOCAL storage — no external hotlinks. Pexels License
 * (free for use; attribution appreciated) — see DEMO-IMAGES.md.
 *   IMPORTANT: stock/model imagery used as illustrative demo content; it is
 *   NOT verified photography of the actual merchandise. Replace with real
 *   catalog shoots before any production launch.
 *
 * Integrity guarantees:
 *   - Products that already have image records are NEVER touched (the DB
 *     check below skips them; re-running is safe and adds nothing).
 *   - Categories without an approved manifest entry are SKIPPED and reported
 *     as pending — never filled with unrelated imagery.
 *   - No schema changes; inserts follow ERD-DATABASE.md §product_images.
 *
 * Usage (from project root, with MySQL running):
 *   php database/seeders/fetch-demo-images.php host port db user pass [table_prefix]
 *   e.g. php database/seeders/fetch-demo-images.php 127.0.0.1 3306 mutya_store root ""
 */
$host = $argv[1] ?? '127.0.0.1';
$port = (int) ($argv[2] ?? 3306);
$dbName = $argv[3] ?? 'mutya_store';
$user = $argv[4] ?? 'root';
$pass = $argv[5] ?? '';

$root = dirname(__DIR__, 2);
$productsDir = $root.'/storage/app/public/products';
if (! is_dir($productsDir)) {
    mkdir($productsDir, 0775, true);
}

try {
    $pdo = new PDO("mysql:host={$host};port={$port};dbname={$dbName};charset=utf8mb4", $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);
} catch (PDOException $e) {
    fwrite(STDERR, "DB connection failed: {$e->getMessage()}\n");
    fwrite(STDERR, "Re-run with your Laragon credentials: php {$argv[0]} host port db user pass\n");
    exit(1);
}

// Curated hijab/modest-fashion photography per category slug.
// Single source of truth: DemoImageManifest.php (same directory).
require_once __DIR__.'/DemoImageManifest.php';
$categoryPhotos = DemoImageManifest::CATEGORY_PHOTOS;

$products = $pdo->query(
    'SELECT p.id, p.name, p.slug, p.material, c.slug AS cat_slug,
            (SELECT COUNT(*) FROM product_images pi WHERE pi.product_id = p.id) AS img_count
     FROM products p LEFT JOIN categories c ON c.id = p.category_id
     ORDER BY p.id'
)->fetchAll(PDO::FETCH_ASSOC);

$pending = [];
foreach ($products as $p) {
    if ((int) $p['img_count'] > 0) {
        echo "SKIP   #{$p['id']} {$p['name']} (already has images)\n";

        continue;
    }
    $pending[] = $p;
}

if ($pending === []) {
    echo "\nAll products already have images — nothing to do.\n";
    exit(0);
}

echo "\nFetching demo image(s) from curated Pexels manifest ...\n\n";

$sqlFile = $root.'/database/seeders/demo-product-images.sql';
$sqlLines = ['-- Auto-generated by fetch-demo-images.php — curated Pexels demo images (see DEMO-IMAGES.md).',
    '-- Illustrative stock imagery only — NOT verified photos of actual merchandise.',
    '-- Reversible: DELETE FROM product_images WHERE image_path LIKE \'products/demo-%\';', ''];

$ctx = stream_context_create(['http' => ['follow_location' => 1, 'timeout' => 20, 'user_agent' => 'Mozilla/5.0 (Mutya dev seeder)']]);
$okCount = 0;

foreach ($pending as $p) {
    $entry = $categoryPhotos[$p['cat_slug']] ?? null;

    if ($entry === null) {
        echo "PEND   #{$p['id']} {$p['name']} — category '{$p['cat_slug']}' has no approved imagery yet.".
            " Add a curated entry to DemoImageManifest.php or upload via Admin (never auto-filled).\n";

        continue;
    }

    $url = DemoImageManifest::cdnUrl($entry['pexels_id']);
    $body = @file_get_contents($url, false, $ctx);

    // Magic-byte check: JPEG FF D8 FF or PNG 89 50 4E 47.
    $isImage = $body !== false && strlen($body) > 5000
        && (substr($body, 0, 3) === "\xFF\xD8\xFF" || substr($body, 0, 4) === "\x89PNG");

    if (! $isImage) {
        echo "FAIL   #{$p['id']} {$p['name']} — could not download ({$url}). Re-run later.\n";

        continue;
    }

    $filename = 'demo-'.$p['slug'].'.jpg';
    $relPath = 'products/'.$filename;
    file_put_contents($productsDir.'/'.$filename, $body);

    $alt = addslashes($p['name'].' — '.($p['material'] ?? 'Mutya Store').' (demo image)');
    $path = addslashes($relPath);
    $sqlLines[] = "-- Pexels #{$entry['pexels_id']} (".DemoImageManifest::sourcePageUrl($entry['pexels_id']).") — Pexels License\n".
        "INSERT INTO product_images (product_id, variant_id, image_path, alt_text, sort_order, is_primary, created_at, updated_at)\n".
        " VALUES ({$p['id']}, NULL, '{$path}', '{$alt}', 0, 1, NOW(), NOW());";

    echo "OK     #{$p['id']} {$p['name']} -> {$relPath} (Pexels #{$entry['pexels_id']})\n";
    $okCount++;
}

file_put_contents($sqlFile, implode("\n", $sqlLines)."\n");

echo "\nDownloaded {$okCount} image(s).\n";
echo 'SQL written to: '.basename($sqlFile)." (in database/seeders/)\n";
echo "Next steps:\n";
echo "  1. Import the SQL:  mysql -u {$user} -p {$dbName} < database/seeders/demo-product-images.sql\n";
echo "     (or paste it into Laragon's phpMyAdmin / Adminer)\n";
echo "  2. Ensure the symlink exists:  php artisan storage:link\n";
echo "  3. Reload the homepage.\n";
